In [2]:
import numpy as np
import pandas as pd


In [3]:
crash = pd.read_csv('MarylandStatewideCrashdata2015-2016.csv')
roads = pd.read_csv('Roads_and_speed_limits_new.csv')
spd = pd.read_csv('speedLimit_time_data.csv')

spd.head()

Speed Lim     20         30     40    50    60     70  Unnamed: 7  \
0         0  116.6  44.500000  112.0  14.4  96.4   71.0         NaN   
1         1   56.6  30.333333  101.4   6.2  54.6   37.0         NaN   
2         2   53.6  21.833333   86.2   3.8  37.0   38.0         NaN   
3         3   63.4  26.000000   97.2   6.6  30.8   73.0         NaN   
4         4   95.2  59.833333   95.4   8.2  70.2  239.0         NaN   

   Unnamed: 8  Unnamed: 9  Unnamed: 10  Unnamed: 11  Unnamed: 12  Unnamed: 13  \
0         NaN         NaN          NaN          NaN          NaN          NaN   
1         NaN         NaN          NaN          NaN          NaN          NaN   
2         NaN         NaN          NaN          NaN          NaN          NaN   
3         NaN         NaN          NaN          NaN          NaN          NaN   
4         NaN         NaN          NaN          NaN          NaN          NaN   

   Unnamed: 14  Unnamed: 15  Unnamed: 16  Unnamed: 17  Unnamed: 18  \
0          NaN          NaN          NaN          NaN          NaN   
1          NaN          NaN          NaN          NaN          NaN   
2          NaN          NaN          NaN          NaN          NaN   
3          NaN          NaN          NaN          NaN          NaN   
4          NaN          NaN          NaN          NaN          NaN   

   Unnamed: 19  
0          NaN  
1          NaN  
2          NaN  
3          NaN  
4          NaN

In [4]:
def RidNaN(a):
    a = np.array(a)
    a.shape
    #a = np.unique(a)

    q = []
    type(a[a.shape[0]-1])
    for i in range(a.shape[0]):
        if(type(a[i]) == float):
            q = np.append(q,i)

    a = np.delete(a,q)
    return a


In [5]:
a = np.array(crash)
a[:,0]
b = np.where(a[:,0] == 0)

d = np.array([0,2,3,5,6.01,7.01,8.04,9.04,10.04,11.88,12.04,88,99])
d[0]


0.0

In [6]:
np.where(a[:,0] == 0)[0]

array([     9,     16,     29, ..., 228082, 228096, 228103], dtype=int64)

In [7]:
e = a[:,0]
for i in range(d.shape[0]):
    e[np.where(a[:,0] == d[i])[0]] = i

In [8]:
e = np.expand_dims(e,axis=1)
e[:,0]

array([2, 5, 4, ..., nan, nan, nan], dtype=object)

In [9]:
e[:,0].shape

(255672,)

In [10]:
a[:,3].shape

(255672,)

In [11]:
f = np.array(roads)
k=[]
count = 0
print(f.shape[0])
for i in range(a[:,3].shape[0]):
    count += 1
    if(a[:,3][i] in f[:,1]):
        k = np.append(k,i)
        

1004


In [12]:
j = k.astype(np.int32)
j

array([    11,   2035,   2036, ..., 228106, 228107, 228108])

In [13]:
a[:,3][j].shape

(112294,)

In [14]:
h = a[:,3][j]
u = np.zeros(shape=(112387,))
f.shape

(1004, 3)

In [15]:
p = []
for i in range (h.shape[0]):
    p = np.append(p,np.where(f[:,1]==h[i])[0][0])

In [17]:
r = a[:,4][j]
r[r > 365] -= 365
r

array([175.0, 185.0, 213.0, ..., 32.0, 217.0, 335.0], dtype=object)

In [18]:
p = p.astype(int)
o = f[p,2]
print(f[p,2])
print(f[p,2].shape,r.shape)
print(f[[p,1]])

[20 20 20 ... 30 30 30]
(112294,) (112294,)
['FALLS RD' '15TH ST' '15TH ST' ... 'ZION CHURCH RD' 'ZION CHURCH RD'
 'ZION CHURCH RD']


C:\Users\vulnic\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  """


In [19]:
a[:,4][j]

array([540.0, 185.0, 213.0, ..., 397.0, 582.0, 700.0], dtype=object)

In [20]:
L = np.around((23*a[:,2][j]).astype(np.double)).astype(int)

In [21]:
s = np.array(spd)
s=s[0:24,1:7]
s.shape

op = o-20
op = op/10
op = op.astype(int)
op

array([0, 0, 0, ..., 1, 1, 1])

In [22]:
np.where(L==23)

(array([    53,    168,    169, ..., 112124, 112134, 112256], dtype=int64),)

In [23]:
percents = []
for i in range(op.shape[0]):
    jkl = s[L[i],op[i]]
    percents = np.append(percents,1/jkl)

In [24]:
percents.shape

(112294,)

In [25]:
jkl = s[L[0],op[0]]
1/jkl

0.0009956192751891678

In [26]:
dataset = pd.DataFrame({'WEATHER_CODE':e[:,0][j],'ACC_DATE':a[:,1][j],'ACC_TIME':L,'MAINROAD_NAME':h,'DATE_VALUE':r,'SPEED_LIMIT':o,'PERCENTAGE':percents})
dataset.head()

WEATHER_CODE   ACC_DATE  ACC_TIME MAINROAD_NAME DATE_VALUE SPEED_LIMIT  \
0            5  6/24/2016        16      FALLS RD        175          20   
1            4   7/5/2015        11       15TH ST        185          20   
2            4   8/2/2015        13       15TH ST        213          20   
3            4  7/31/2016        11       15TH ST        212          20   
4            4  9/16/2016        15       15TH ST        259          20   

   PERCENTAGE  
0    0.000996  
1    0.001516  
2    0.001496  
3    0.001516  
4    0.001132

In [448]:
dataset.to_csv('./Train.csv')

In [27]:
np.where()

array(['FALLS RD', '15TH ST', '15TH ST', ..., 'ZION CHURCH RD',
       'ZION CHURCH RD', 'ZION CHURCH RD'], dtype=object)

In [38]:
asd = np.array(asd)


NameError: name 'shape' is not defined

In [34]:
df = pd.DataFrame({'Name':asd[0],'Abbreviation':asd[1]})

ValueError: arrays must all be same length

In [40]:
df = pd.read_csv('library/Roads_and_speed_limits_new.csv')
rd_sp = np.array(df['Roads'])

In [41]:
'15TH ST' in rd_sp

True

In [44]:
np.where('15TH ST' == rd_sp)[0][0]

0

In [47]:
df.head()

Unnamed: 0       Roads  Speed Limit
0           0     15TH ST           20
1           1     16TH ST           40
2           2     38TH ST           40
3           3  4H PARK RD           20
4           4    57TH AVE           40