In [392]:
import numpy as np
import pandas as pd


In [393]:
speed_limits = pd.read_csv('Maryland_Roadway_Posted_Speed_Limits__Roadway_Posted_Speed_Limit_Signs.csv')
crash_data = pd.read_csv('MarylandStatewideCrashdata2015-2016.csv')
AADT_data = pd.read_csv('Maryland_Annual_Average_Daily_Traffic__Annual_Average_Daily_Traffic_SHA_Statewide_AADT_Points.csv')


In [394]:
AADT_rd = AADT_data['ROADNAME']
car_usage_2015 = AADT_data['AAWDT_2015_ANNO']
car_usage_2016 = AADT_data['AAWDT_2016_ANNO']

In [395]:
rd_nm = speed_limits['ROAD_NAME']
sd_nm = speed_limits['SPEED_LIMIT']

X = speed_limits['X']
y = speed_limits['Y']

In [396]:
X_cr = crash_data['LATITUDE']
Y_cr = crash_data['LONGITUDE']

acc_date = crash_data['ACC_DATE']
acc_date = crash_data['ACC_TIME']

main_road = crash_data['MAINROAD_NAME']
ref_road = crash_data['REFERENCE_ROAD_NAME']


In [476]:
def RidNaN(a):
    a = np.array(a)
    a.shape
    #a = np.unique(a)

    q = []
    type(a[a.shape[0]-1])
    for i in range(a.shape[0]):
        if(type(a[i]) == float):
            q = np.append(q,i)

    a = np.delete(a,q)
    return a


In [453]:
def whereAreNames(a):
    u = []
    for i in range(road_names_final_F.shape[0]):
        l = np.where(a == road_names_final_F[i])
        u = np.append(u,l)
    return u

In [473]:
def stripEveryString(a):
    for i in range(a.shape[0]):
        if ' ' in a[i]:
            a[i] = str.strip(a[i])
    return a

In [487]:
def booleanMap(rd_array, rd_name_collection):
    boolean_array = []
    for i in range(rd_array.shape[0]):
        if(np.any(rd_array[i] in rd_name_collection)):
            boolean_array = np.append(boolean_array,True)
        else:
            boolean_array = np.append(boolean_array,False)
            
    return boolean_array

In [491]:
speed_limit_rd_pre = np.array(rd_nm)
speed_limit_rd = np.unique(speed_limit_rd_pre)
speed_limit_rd.shape

(1815,)

In [492]:
cras_roads_pre = RidNaN(main_road)
cras_roads = np.unique(cras_roads_pre)
cras_roads = stripEveryString(cras_roads)
cras_roads

C:\Users\vulnic\Anaconda3\lib\site-packages\ipykernel_launcher.py:12: DeprecationWarning: using a non-integer array as obj in delete will result in an error in the future
  if sys.path[0] == '':


array(['FALLS RD', 'I-395', '4100 BLK MORRISON CT', ..., 'ZION CHURCH RD',
       'ZION RD', 'ZOLL LA'], dtype=object)

In [493]:
boolean_array = booleanMap(cras_roads,speed_limit_rd)
g = np.where(boolean_array == 1)
road_names_final = []
road_names_final = np.append(road_names_final,cras_roads[g])
road_names_final.shape   

(1234,)

In [488]:
AADT_final_rd = RidNaN(AADT_rd)
AADT_final_rd = np.unique(AADT_final_rd)
AADT_final_rd = stripEveryString(AADT_final_rd)
AADT_final_rd

C:\Users\vulnic\Anaconda3\lib\site-packages\ipykernel_launcher.py:12: DeprecationWarning: using a non-integer array as obj in delete will result in an error in the future
  if sys.path[0] == '':


array(['10TH AVE', '10TH ST', '15TH ST', ..., 'YORK ST', 'ZION CHURCH RD',
       'ZION RD'], dtype=object)

In [489]:
boolean_array_final = booleanMap(AADT_final_rd,road_names_final)
g = np.where(boolean_array_final == 1)
g

(array([   2,    3,   11, ..., 5917, 5918, 5919], dtype=int64),)

In [490]:
road_names_final_F = []
road_names_final_F = np.append(road_names_final_F,AADT_final_rd[g])
road_names_final_F.shape

(1004,)

In [494]:
count = 0
k = []
for i in range(speed_limit_rd.shape[0]):
    if(speed_limit_rd[i] in road_names_final_F):
        #k = np.append(k,cras_roads_pre[i])
        count +=1
        #if(count%500 == 0):
        #    print(count)
count

1004

In [516]:
u = whereAreNames(speed_limit_rd_pre)
u = u.astype(np.int16)
print(u.shape)

sd = np.array(sd_nm)
e = sd[u]
o = speed_limit_rd_pre[u]
print(e.shape)

t = RidNaN(AADT_rd)
t = stripEveryString(t)
c = whereAreNames(t)
c = c.astype(np.int32)
t[c]

print(c.shape)

(3241,)
(3241,)
(3026,)


C:\Users\vulnic\Anaconda3\lib\site-packages\ipykernel_launcher.py:12: DeprecationWarning: using a non-integer array as obj in delete will result in an error in the future
  if sys.path[0] == '':


In [520]:
print(o)
print(e)
o[0]

['15TH ST' '15TH ST' '15TH ST' ... 'YORK ST' 'YORK ST' 'ZION CHURCH RD']
[30 25 25 ... 15 25 30]


'15TH ST'

In [506]:
road_names_final_F.shape

(1004,)

In [526]:
o[o.shape[0]-1]

'ZION CHURCH RD'

In [677]:
temp = [e[0]]
avg = []
for i in range(o.shape[0]-1):
    if(o[i] == o[i+1]):
        temp = np.append(e[i],temp)
    elif(o[i] != o[i+1]):
        avg = np.append(np.average(temp),avg)
        temp = [e[i+1]]
    


In [678]:
avg = np.append(avg,e[o.shape[0]-1])
avg[1003]
e[e.shape[0]-1]

30

In [679]:
print(road_names_final)
print(avg)

['FALLS RD' 'ANNAPOLIS RD' 'BOSTON ST' ... 'YORK ST' 'YOUNG RD'
 'ZION CHURCH RD']
[21.66666667 36.92307692 40.         ... 35.         28.33333333
 30.        ]


In [680]:
j = road_names_final_F
j = np.expand_dims(j,axis=1)
avg = np.expand_dims(avg,axis=1)

print(j.shape,avg.shape)
j = np.append(j,avg,axis=1)
j

(1004, 1) (1004, 1)


array([['15TH ST', 21.666666666666668],
       ['16TH ST', 36.92307692307692],
       ['38TH ST', 40.0],
       ...,
       ['YORK RD', 35.0],
       ['YORK ST', 28.333333333333332],
       ['ZION CHURCH RD', 30.0]], dtype=object)

In [681]:
dataset = pd.DataFrame({'Roads':j[:,0],'Speed Limit':j[:,1]})
dataset.head()

Roads Speed Limit
0     15TH ST     21.6667
1     16TH ST     36.9231
2     38TH ST          40
3  4H PARK RD          25
4    57TH AVE     36.6667

In [682]:
dataset.to_csv('./Roads_and_speed_limits')

In [683]:
for i in range (j.shape[0]):
    j[i,1] = int(round(j[i,1]/10,0))*10
        

In [689]:
print(np.unique(j[:,1]))

[20 30 40 50 60 70]


In [690]:
dataset = pd.DataFrame({'Roads':j[:,0],'Speed Limit':j[:,1]})
dataset.head()

Roads Speed Limit
0     15TH ST          20
1     16TH ST          40
2     38TH ST          40
3  4H PARK RD          20
4    57TH AVE          40

In [691]:
dataset.to_csv('./Roads_and_speed_limits_new')